### ISSUE TITLE
plugin in not working 

### ISSUE THREAD

**Issue by gigabyteservice** [gossamr/jitsi-token-muc-max-occupants-plugin#1]
Either this plugin is not working or I don't know how to enable this properly or else it's needed the support of muc_max_occupants plugin.

I have added  this line to enable the prosody module into the config file (the version of Prosody 0.11.7, lua 5.2 )

Component "conference.app.example.com" "muc"
    storage = "memory"
    modules_enabled = {
       ......
      ........
      .........
		"token_muc_max_occupants";
      ........
      ......
    }

restarts everything 

I can see "token_muc_max_occupants	info	Loaded token max muc occupants plugin" message in the prosody log 
that means I have enabled this plugin and it's running because this line was written in the plugin but when passing this value in JWT token's payload  
 e.g
"max_occ": 4, 

this token is pass and the user can enter into that other participant can enter into that room but both users are not connecting with each other.

Please share proper documentation for the installation of this plugin
thank you

**Comment by gossamr** [comment]
This plugin embeds and expands on the relevant parts of muc_max_occupants and has the same config on the Jitsi side. Make sure you set muc_access_whitelist as you would with muc_max_occupants.
